# Generated by Django 4.1.7 on 2023-03-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=2),
        ),
    ]
